services:
  postgres:
    image: postgres:17
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - postgres:/var/lib/postgresql/data

  golang-project:
    container_name: "my-project"
    build:
      context: ./
      dockerfile: Dockerfile
    image: golang-project
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env.example
    ports:
      - "8080:8080"

volumes:
  postgres:
