services:
  postgres:
    image: postgres:17
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  # localstack:
  #   image: localstack/localstack:latest
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
  #   environment:
  #     - SERVICES=s3
  #     - DEBUG=1
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"

  # bucket_creator:
  #   image: amazon/aws_cli
  #   entrypoint: /bin/sh -c "sleep 5; aws --no-sign-request --region us-east-1 --endpoint-url:http://localstack:4566 s3 mb s3://photo-bucket"
  #   depends_on:
  #     - localstack

  # uploader:
  #   build: .
  #   environment:
  #     - AWS_REGION=us-east-1
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #     - AWS_ENDPOINT="http://localstack:4566"
  #   depends_on:
  #     - bucket_creator

  golang-project:
    container_name: "my-project"
    build:
      context: ./
      dockerfile: Dockerfile
    image: golang-project
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env.example
    ports:
      - "8080:8080"

volumes:
  postgres:
