CREATE TABLE images (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    path VARCHAR(512) NOT NULL UNIQUE,
    type VARCHAR(5) NOT NULL,
    mimeType VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);